#!/usr/bin/env python3
"""Refresh the reviewed SHA-256 allowlist for every exact Python owner-lock pin.

This maintenance command reads immutable release metadata from PyPI and writes one
deduplicated canonical record per package/version.  Its diff
is intended to be reviewed alongside dependency-update pull requests; CI consumes the
result without consulting mutable package-index metadata.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Sequence

from meta.ci.quality.locked_requirements import read_owner_lock

ROOT = Path(__file__).resolve().parents[3]


def _write_atomically(destination: Path, content: str) -> None:
    """Replace one regular output without following a pre-created path alias."""
    if destination.is_symlink() or (destination.exists() and not destination.is_file()):
        raise ValueError(f"artifact-lock output is unsafe: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _release_artifact_hashes(key: str) -> tuple[str, tuple[str, ...]]:
    """Fetch one release and return every published artifact SHA-256 digest."""
    name, version = key.split("==", 1)
    url = "https://pypi.org/pypi/{}/{}/json".format(
        urllib.parse.quote(name, safe=""), urllib.parse.quote(version, safe="")
    )
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=30) as response:  # nosec B310
        payload = json.load(response)
    hashes = tuple(
        sorted(
            {
                f"sha256:{entry['digests']['sha256']}"
                for entry in payload.get("urls", ())
                if entry.get("digests", {}).get("sha256")
            }
        )
    )
    if not hashes:
        raise RuntimeError(f"PyPI release has no hashed artifacts: {key}")
    return key, hashes


def refresh(requirements_dir: Path, output: Path) -> None:
    """Fetch every unique pinned release and atomically replace the hash allowlist."""
    keys = sorted(
        {
            requirement.key
            for lock in sorted(requirements_dir.glob("*.txt"))
            for requirement in read_owner_lock(lock)
        }
    )
    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
        records = dict(executor.map(_release_artifact_hashes, keys))
    content = (
        "# Generated by meta/ci/quality/refresh_python_artifact_hashes.py.\n"
        "# Review every digest change with its exact owner-lock version update.\n"
        + "".join(f"{key} {' '.join(records[key])}\n" for key in keys)
    )
    _write_atomically(output, content)


def main(argv: Sequence[str] | None = None) -> int:
    """Parse maintenance paths, refresh the allowlist, and return success."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements-dir", type=Path, default=ROOT / "meta/ci/requirements")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "meta/ci/requirements/python-artifact-sha256.lock",
    )
    args = parser.parse_args(argv)
    refresh(args.requirements_dir, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
