"""Regression coverage for v77 progressive one-pass Python replay."""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path

import pytest
from conftest import require_native

import schema_sanitizer as ss
from schema_sanitizer.core_impl import python_rows
from schema_sanitizer.core_impl.concurrency_coverage import (
    INPUT_CONCURRENCY_COVERAGE,
    OUTPUT_CONCURRENCY_COVERAGE,
    concurrency_pair_guarantees,
)
from schema_sanitizer.core_impl.python_rows import PythonRowsJsonlByteReader


def _read_all(reader: PythonRowsJsonlByteReader, chunk_bytes: int = 16_381) -> bytes:
    """Consume one complete logical pass from a generated byte reader."""
    parts: list[bytes] = []
    while payload := reader.read(chunk_bytes):
        parts.append(payload)
    return b"".join(parts)


def test_v77_every_input_output_pair_has_an_integral_parallel_contract() -> None:
    """All eight inputs combine explicitly with all seven outputs."""
    pairs = concurrency_pair_guarantees()
    assert set(pairs) == set(INPUT_CONCURRENCY_COVERAGE)
    assert sum(len(outputs) for outputs in pairs.values()) == 56
    for input_name, outputs in pairs.items():
        assert set(outputs) == set(OUTPUT_CONCURRENCY_COVERAGE)
        for contract in outputs.values():
            assert contract["input_parallel_stages"]
            shared_stages = contract["shared_parallel_stages"]
            assert shared_stages[0] == "operation_owned_task_arena"
            assert shared_stages[-1] == "parallel_arrow_c_stream_handoff"
            assert contract["output_parallel_stages"]
            assert contract["serial_boundaries"]
            assert contract["source_to_sink_parallel_path"] is True
            assert contract["eligible_multi_benefit"] is True
            assert "+" in str(contract["benefit_proof"])
    assert "single_encode_progressive_replay" in pairs["python"]["csv"]["input_parallel_stages"]


def test_v77_sequence_rows_are_encoded_once_across_repeated_replays(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A reusable sequence no longer pays a second native object walk."""
    require_native()
    original = python_rows.PYTHON_ROWS_JSONL_BYTES
    encoded_ranges: list[tuple[int, int]] = []

    def counted(*args: object) -> tuple[bytes, int]:
        """Record each encoded sequence range before returning native bytes."""
        payload, next_index = original(*args)
        encoded_ranges.append((int(args[1]), int(next_index)))
        return payload, int(next_index)

    monkeypatch.setattr(python_rows, "PYTHON_ROWS_JSONL_BYTES", counted)
    rows = [{"ordinal": index, "value": index * 3} for index in range(12_000)]
    reader = PythonRowsJsonlByteReader(rows, memory_limit_bytes=64 << 20)
    prefix = reader.read(8_192)
    reader.seek(0)
    first = _read_all(reader)
    reader.seek(0)
    second = _read_all(reader)
    reader.close()

    assert first.startswith(prefix)
    assert first == second
    assert first.count(b"\n") == len(rows)
    assert sum(stop - start for start, stop in encoded_ranges) == len(rows)


def test_v77_generator_seek_is_progressive_and_never_reiterates() -> None:
    """Schema replay starts immediately instead of draining the generator first."""
    require_native()
    yielded = 0

    def source() -> Iterator[dict[str, int]]:
        """Yield ordered rows while exposing the exact iteration count."""
        nonlocal yielded
        for index in range(12_000):
            yielded += 1
            yield {"ordinal": index, "value": index * 5}

    reader = PythonRowsJsonlByteReader(source(), memory_limit_bytes=64 << 20)
    prefix = reader.read(8_192)
    yielded_after_probe = yielded
    assert 0 < yielded_after_probe < 12_000

    reader.seek(0)
    assert yielded == yielded_after_probe
    assert reader.read(len(prefix)) == prefix
    assert yielded == yielded_after_probe
    first = prefix + _read_all(reader)
    assert yielded == 12_000

    reader.seek(0)
    second = _read_all(reader)
    reader.close()
    assert yielded == 12_000
    assert first == second
    assert second.count(b"\n") == 12_000


@pytest.mark.parametrize(
    ("converter_name", "suffix", "extra"),
    [
        ("to_csv", ".csv", {}),
        ("to_jsonl", ".jsonl", {}),
        ("to_parquet", ".parquet", {"parquet_compression": "uncompressed"}),
    ],
)
def test_v77_single_encode_route_reaches_every_native_output(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    converter_name: str,
    suffix: str,
    extra: dict[str, str],
) -> None:
    """The common one-pass Python source route feeds every native sink."""
    require_native()
    original = python_rows.PYTHON_ROWS_JSONL_BYTES
    encoded_rows = 0

    def counted(*args: object) -> tuple[bytes, int]:
        """Count rows encoded for one native output conversion."""
        nonlocal encoded_rows
        payload, next_index = original(*args)
        encoded_rows += int(next_index) - int(args[1])
        return payload, int(next_index)

    monkeypatch.setattr(python_rows, "PYTHON_ROWS_JSONL_BYTES", counted)
    rows = [{f"field_{column:02d}": row + column for column in range(24)} for row in range(8_000)]
    output = tmp_path / f"result{suffix}"
    result = getattr(ss, converter_name)(
        rows,
        output,
        input_format="python",
        threading_mode="multi",
        memory_limit_bytes=128 << 20,
        **extra,
    )
    assert result.stats["materialized_rows"] == len(rows)
    assert encoded_rows == len(rows)
    assert output.stat().st_size > 0
