"""Require an integral parallel contract for every public input and output pairing.

Python sequences must be encoded only once across replays, one-shot generators must seek without
reiteration, and the shared single-encode route must reach every native output format.
"""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path

import pytest

import schema_sanitizer as ss
from schema_sanitizer.core_impl import python_rows
from schema_sanitizer.core_impl.concurrency_coverage import (
    INPUT_CONCURRENCY_COVERAGE,
    OUTPUT_CONCURRENCY_COVERAGE,
    concurrency_pair_guarantees,
)
from schema_sanitizer.core_impl.python_rows import PythonRowsJsonlByteReader

EXPECTED_SHARED_PARALLEL_STAGES = (
    "operation_owned_task_arena",
    "gil_released_native_wait_boundaries",
    "cacheline_isolated_arena_writer_domains",
    "worker_active_streak_accounting",
    "cacheline_isolated_worker_running_publication",
    "sparse_bitset_round_robin_worker_selection",
    "single_modulo_lane_origin_reuse",
    "worker_local_monotonic_peak_active_cache",
    "single_store_worker_active_streak_telemetry",
    "cacheline_isolated_worker_wake_epoch_publication",
    "targeted_worker_wake_epochs",
    "running_worker_wake_coalescing",
    "park_boundary_wake_epoch_sampling",
    "telemetry_aware_clock_elision",
    "empty_to_nonempty_queue_visibility",
    "high_core_sharded_queue_visibility",
    "fixed_physical_queue_visibility_snapshot",
    "compact_queued_task_lane_metadata",
    "one_shot_worker_initialization_publication",
    "park_boundary_first_task_sampling",
    "monotonic_initialized_worker_park_snapshot_elision",
    "worker_local_stolen_task_accounting",
    "single_store_worker_local_stolen_publication",
    "authoritative_started_mask_start_lock_elision",
    "initialized_worker_snapshot_admission_elision",
    "precompiled_stage_submission_plan",
    "modulo_free_ordered_completion_ring",
    "slot_terminal_state_pre_wait_coordination",
    "single_rmw_external_task_lifetime_accounting",
    "worker_sharded_submission_accounting",
    "mutex_owned_queue_counters_single_store_publication",
    "successful_drain_only_queue_visibility_publication",
    "worker_count_sharded_external_completion_accounting",
    "shutdown_waiter_bit_external_completion_notification_elision",
    "single_sentinel_external_task_lease_completion",
    "compile_time_abandonment_single_shard_lease",
    "typed_owner_member_abandonment_lease",
    "single_snapshot_arena_terminal_flags",
    "stop_token_authoritative_high_core_worker_loop",
    "high_core_executor_local_arena_submission_tickets",
    "high_core_single_writer_in_flight_publication",
    "mutex_owned_memory_order_tightening",
    "high_core_single_writer_in_flight_consumption",
    "low_core_worker_sharded_task_telemetry",
    "single_store_worker_local_task_telemetry_publication",
    "all_worker_sharded_task_completion_telemetry",
    "single_store_worker_sharded_submission_telemetry",
    "transferable_resident_memory_credit",
    "composite_slot_and_byte_admission",
    "process_control_plane_budget",
    "parallel_arrow_c_stream_handoff",
)


def _read_all(reader: PythonRowsJsonlByteReader, chunk_bytes: int = 16_381) -> bytes:
    """Consume one complete logical pass from a generated byte reader."""
    parts: list[bytes] = []
    while payload := reader.read(chunk_bytes):
        parts.append(payload)
    return b"".join(parts)


def test_every_input_output_pair_has_an_integral_parallel_contract() -> None:
    """All seven inputs combine explicitly with all seven outputs."""
    pairs = concurrency_pair_guarantees()
    assert set(pairs) == set(INPUT_CONCURRENCY_COVERAGE)
    assert sum(len(outputs) for outputs in pairs.values()) == 49
    for input_name, outputs in pairs.items():
        assert set(outputs) == set(OUTPUT_CONCURRENCY_COVERAGE)
        for contract in outputs.values():
            assert contract["input_parallel_stages"]
            assert contract["shared_parallel_stages"] == EXPECTED_SHARED_PARALLEL_STAGES
            assert contract["output_parallel_stages"]
            assert contract["serial_boundaries"]
            assert contract["source_to_sink_parallel_path"] is True
            assert contract["eligible_multi_benefit"] is True
            assert "+" in str(contract["benefit_proof"])
    assert "single_encode_progressive_replay" in pairs["python"]["csv"]["input_parallel_stages"]


def test_sequence_rows_are_encoded_once_across_repeated_replays(
    monkeypatch: pytest.MonkeyPatch,
    require_native: None,
) -> None:
    """A reusable sequence pays for one native object walk."""
    original = python_rows.PYTHON_ROWS_JSONL_BYTES
    encoded_ranges: list[tuple[int, int]] = []

    def counted(*args: object) -> tuple[bytes, int]:
        """Record each encoded sequence range before returning native bytes."""
        payload, next_index = original(*args)
        encoded_ranges.append((int(args[1]), int(next_index)))
        return payload, int(next_index)

    monkeypatch.setattr(python_rows, "PYTHON_ROWS_JSONL_BYTES", counted)
    rows = [{"ordinal": index, "value": index * 3} for index in range(12_000)]
    reader = PythonRowsJsonlByteReader(rows, memory_limit_bytes=64 << 20)
    prefix = reader.read(8_192)
    reader.seek(0)
    first = _read_all(reader)
    reader.seek(0)
    second = _read_all(reader)
    reader.close()

    assert first.startswith(prefix)
    assert first == second
    assert first.count(b"\n") == len(rows)
    assert sum(stop - start for start, stop in encoded_ranges) == len(rows)


def test_generator_seek_is_progressive_and_never_reiterates(require_native: None) -> None:
    """Schema replay starts immediately instead of draining the generator first."""
    yielded = 0

    def source() -> Iterator[dict[str, int]]:
        """Yield ordered rows while exposing the exact iteration count."""
        nonlocal yielded
        for index in range(12_000):
            yielded += 1
            yield {"ordinal": index, "value": index * 5}

    reader = PythonRowsJsonlByteReader(source(), memory_limit_bytes=64 << 20)
    prefix = reader.read(8_192)
    yielded_after_probe = yielded
    assert 0 < yielded_after_probe < 12_000

    reader.seek(0)
    assert yielded == yielded_after_probe
    assert reader.read(len(prefix)) == prefix
    assert yielded == yielded_after_probe
    first = prefix + _read_all(reader)
    assert yielded == 12_000

    reader.seek(0)
    second = _read_all(reader)
    reader.close()
    assert yielded == 12_000
    assert first == second
    assert second.count(b"\n") == 12_000


@pytest.mark.parametrize(
    ("converter_name", "suffix", "extra"),
    [
        ("to_csv", ".csv", {}),
        ("to_jsonl", ".jsonl", {}),
        ("to_parquet", ".parquet", {"parquet_compression": "uncompressed"}),
    ],
)
def test_single_encode_route_reaches_every_native_output(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    converter_name: str,
    suffix: str,
    extra: dict[str, str],
    require_native: None,
) -> None:
    """The common one-pass Python source route feeds every native sink."""
    original = python_rows.PYTHON_ROWS_JSONL_BYTES
    encoded_rows = 0

    def counted(*args: object) -> tuple[bytes, int]:
        """Count rows encoded for one native output conversion."""
        nonlocal encoded_rows
        payload, next_index = original(*args)
        encoded_rows += int(next_index) - int(args[1])
        return payload, int(next_index)

    monkeypatch.setattr(python_rows, "PYTHON_ROWS_JSONL_BYTES", counted)
    rows = [{f"field_{column:02d}": row + column for column in range(24)} for row in range(8_000)]
    output = tmp_path / f"result{suffix}"
    result = getattr(ss, converter_name)(
        rows,
        output,
        input_format="python",
        multi_threading=True,
        memory_limit_bytes=128 << 20,
        **extra,
    )
    assert result.stats["materialized_rows"] == len(rows)
    assert encoded_rows == len(rows)
    assert output.stat().st_size > 0
