"""Keep project documentation stable, navigable, and internally consistent."""

from __future__ import annotations

import ast
import re
from collections.abc import Iterator
from pathlib import Path
from urllib.parse import unquote, urlsplit

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = PROJECT_ROOT / "docs"
DOCS_INDEX = DOCS_ROOT / "README.md"
DOC_SECTIONS = frozenset({"guides", "internals", "operations", "project", "reference"})
DOCUMENTATION = tuple(sorted(DOCS_ROOT.rglob("*.md")))
MARKDOWN = (PROJECT_ROOT / "README.md", *DOCUMENTATION)
INLINE_LINK = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")
HEADING = re.compile(r"^#{1,6}\s+(.+?)\s*$")
NUMBERED_DESIGN_FILE = re.compile(r"(?:^|[-_])(?:pass|phase|version|v)[-_]?\d", re.IGNORECASE)
PYTHON_FENCE = re.compile(r"```python\n(.*?)\n```", re.DOTALL)
PUBLIC_FACADES = (
    PROJECT_ROOT / "src/schema_sanitizer/__init__.py",
    PROJECT_ROOT / "src/schema_sanitizer/sources/__init__.py",
    PROJECT_ROOT / "src/schema_sanitizer/pipeline/__init__.py",
    PROJECT_ROOT / "src/schema_sanitizer/integrations/bigquery/__init__.py",
)
CONVERTER_MODULES = {
    PROJECT_ROOT / "src/schema_sanitizer/api_impl/analytical.py": {
        "to_duckdb",
        "to_pandas",
        "to_polars",
        "to_pyarrow",
    },
    PROJECT_ROOT / "src/schema_sanitizer/api_impl/batch_streaming.py": {"iter_batches"},
    PROJECT_ROOT / "src/schema_sanitizer/api_impl/file_conversion/converters.py": {
        "to_csv",
        "to_jsonl",
        "to_parquet",
    },
}


def _markdown_lines(path: Path) -> Iterator[str]:
    """Yield Markdown outside fenced code blocks."""
    fenced = False
    fence = ""
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.lstrip()
        if not fenced and stripped.startswith(("```", "~~~")):
            fenced = True
            fence = stripped[:3]
            continue
        if fenced and stripped.startswith(fence):
            fenced = False
            fence = ""
            continue
        if not fenced:
            yield line


def _local_links(path: Path) -> Iterator[tuple[str, str]]:
    """Yield decoded local link paths and fragments from one Markdown file."""
    for line in _markdown_lines(path):
        for match in INLINE_LINK.finditer(line):
            destination = match.group(1).strip()
            if destination.startswith("<") and ">" in destination:
                destination = destination[1 : destination.index(">")]
            else:
                destination = destination.split(maxsplit=1)[0]
            parsed = urlsplit(destination)
            if parsed.scheme or parsed.netloc:
                continue
            yield unquote(parsed.path), unquote(parsed.fragment)


def _heading_anchors(path: Path) -> set[str]:
    """Return the GitHub-style anchors generated by headings in one file."""
    anchors: set[str] = set()
    occurrences: dict[str, int] = {}
    for line in _markdown_lines(path):
        match = HEADING.match(line)
        if match is None:
            continue
        title = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", match.group(1))
        title = re.sub(r"<[^>]+>", "", title).replace("`", "").lower()
        base = re.sub(r"\s+", "-", re.sub(r"[^\w\- ]", "", title).strip())
        duplicate = occurrences.get(base, 0)
        occurrences[base] = duplicate + 1
        anchors.add(base if duplicate == 0 else f"{base}-{duplicate}")
    return anchors


def _resolve_link(source: Path, relative: str) -> Path:
    """Resolve a local Markdown destination relative to its source file."""
    return (source.parent / relative).resolve() if relative else source.resolve()


def _literal_exports(path: Path) -> tuple[str, ...]:
    """Read one static ``__all__`` without importing native-backed modules."""
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in module.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            value = ast.literal_eval(node.value)
            assert isinstance(value, list)
            return tuple(value)
    raise AssertionError(f"missing static __all__: {path}")


def _public_converter_parameters() -> set[str]:
    """Return public converter parameters directly from their source signatures."""
    parameters: set[str] = set()
    for path, names in CONVERTER_MODULES.items():
        module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        found: set[str] = set()
        for node in module.body:
            if (
                not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
                or node.name not in names
            ):
                continue
            found.add(node.name)
            parameters.update(argument.arg for argument in node.args.posonlyargs)
            parameters.update(argument.arg for argument in node.args.args)
            parameters.update(argument.arg for argument in node.args.kwonlyargs)
        assert found == names, (path, found, names)
    return parameters


def test_only_introductory_readme_remains_at_repository_root() -> None:
    """Detailed Markdown belongs under docs instead of the repository root."""
    root_markdown = sorted(path.name for path in PROJECT_ROOT.glob("*.md"))

    assert root_markdown == ["README.md"]


def test_documentation_tree_matches_the_supported_hierarchy() -> None:
    """Detailed documentation stays in the indexed topic-oriented sections."""
    relative = {path.relative_to(DOCS_ROOT) for path in DOCUMENTATION}

    assert DOCS_INDEX in DOCUMENTATION
    assert {path.parts[0] for path in relative - {Path("README.md")}} == DOC_SECTIONS
    assert all(len(path.parts) == 2 for path in relative - {Path("README.md")})


def test_documentation_index_links_every_document() -> None:
    """The root docs index reaches every guide, including nested topics."""
    linked: set[Path] = set()
    for relative, _fragment in _local_links(DOCS_INDEX):
        if not relative:
            continue
        target = _resolve_link(DOCS_INDEX, relative)
        if target != DOCS_INDEX and target.is_relative_to(DOCS_ROOT) and target.suffix == ".md":
            linked.add(target.relative_to(DOCS_ROOT))

    actual = {path.relative_to(DOCS_ROOT) for path in DOCUMENTATION}
    assert linked == actual - {Path("README.md")}


def test_docs_do_not_use_numbered_design_filenames() -> None:
    """Stable topics replace pass-, phase-, and version-numbered design files."""
    offenders = sorted(
        path.relative_to(DOCS_ROOT).as_posix()
        for path in DOCUMENTATION
        if NUMBERED_DESIGN_FILE.search(path.stem)
    )

    assert offenders == []


def test_local_markdown_links_and_anchors_resolve() -> None:
    """Every local link stays inside the project and resolves to a real target."""
    for source in MARKDOWN:
        for relative, fragment in _local_links(source):
            target = _resolve_link(source, relative)
            assert target.is_relative_to(PROJECT_ROOT), (source, relative)
            assert target.exists(), (source, relative)
            if fragment:
                assert target.is_file() and target.suffix.lower() == ".md", (
                    source,
                    relative,
                    fragment,
                )
                assert fragment in _heading_anchors(target), (source, relative, fragment)


def test_python_examples_are_syntactically_current() -> None:
    """Every Python fence remains valid syntax on the supported interpreter."""
    for path in MARKDOWN:
        for index, source in enumerate(PYTHON_FENCE.findall(path.read_text(encoding="utf-8")), 1):
            compile(source, f"{path}:python-block-{index}", "exec")


def test_public_facade_exports_are_documented() -> None:
    """Every curated public name remains discoverable in the documentation."""
    documentation = "\n".join(path.read_text(encoding="utf-8") for path in DOCUMENTATION)
    missing: list[tuple[Path, str]] = []
    for facade in PUBLIC_FACADES:
        for name in _literal_exports(facade):
            if re.search(rf"(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])", documentation):
                continue
            missing.append((facade.relative_to(PROJECT_ROOT), name))
    assert missing == []


def test_options_reference_covers_public_converter_parameters() -> None:
    """The option table cannot silently omit a newly added converter argument."""
    reference = (DOCS_ROOT / "reference/options.md").read_text(encoding="utf-8")
    documented = set(re.findall(r"^\| `([a-z][a-z0-9_]*)` \|", reference, re.MULTILINE))

    assert _public_converter_parameters() <= documented
