"""Shared seekable buffered byte-reader base classes."""

from __future__ import annotations

from contextlib import suppress


class BufferedSeekableByteReader:
    """Reusable read/seek/close lifecycle for generated byte streams."""

    def __init__(self, reader_name: str, *, default_chunk_bytes: int):
        """Initialize shared buffered reader state."""
        self._reader_name = reader_name
        self._default_chunk_bytes = default_chunk_bytes
        self._buffer = bytearray()
        self._closed = False

    def _append_next(self, target_bytes: int) -> bool:
        """Append the next source part to the buffer."""
        raise NotImplementedError

    def _reset_reader(self) -> None:
        """Reset subclass source position to the beginning."""
        raise NotImplementedError

    def read(self, max_bytes: int = -1, /) -> bytes:
        """Return up to max_bytes from the generated byte stream."""
        if self._closed:
            raise ValueError(f"I/O operation on closed {self._reader_name}")
        if max_bytes is None or max_bytes < 0:
            max_bytes = self._default_chunk_bytes
        if max_bytes == 0:
            return b""
        while len(self._buffer) < max_bytes:
            if not self._append_next(max_bytes - len(self._buffer)):
                break
        if not self._buffer:
            return b""
        out = bytes(self._buffer[:max_bytes])
        del self._buffer[:max_bytes]
        return out

    def seek(self, offset: int) -> int:
        """Reset the generated byte stream to the beginning."""
        if offset != 0:
            raise ValueError(f"{self._reader_name} only supports seek(0)")
        self._reset_reader()
        self._buffer.clear()
        self._closed = False
        return 0

    def close(self) -> None:
        """Release transient buffered bytes."""
        if self._closed:
            return
        self._closed = True
        self._buffer.clear()

    def __del__(self) -> None:
        """Best-effort release transient buffered bytes."""
        with suppress(Exception):
            self.close()
