"""Reusable lifecycle for replayable generated byte streams."""

from __future__ import annotations

from contextlib import suppress

from .finalization import runtime_is_finalizing

_COMPACT_AFTER_BYTES = 1 << 20
_ZERO_CHUNK = b"\x00" * (1 << 20)


def _secure_cleanup_enabled() -> bool:
    """Return the always-on transient-byte cleanup policy."""
    return True


def _zero_bytearray_range(buffer: bytearray, start: int, end: int) -> None:
    """Overwrite one bytearray range without allocating a same-sized zero buffer."""
    if start < 0 or end <= start:
        return
    view = memoryview(buffer)
    zero_view = memoryview(_ZERO_CHUNK)
    try:
        cursor = start
        while cursor < end:
            next_cursor = min(cursor + len(_ZERO_CHUNK), end)
            view[cursor:next_cursor] = zero_view[: next_cursor - cursor]
            cursor = next_cursor
    finally:
        zero_view.release()
        view.release()


class BufferedGeneratedBytesReader:
    """Read, seek, and close a replayable generated byte stream."""

    def __init__(self, reader_name: str, *, default_chunk_bytes: int):
        """Initialize shared buffered reader state."""
        self._reader_name = reader_name
        self._default_chunk_bytes = default_chunk_bytes
        self._buffer = bytearray()
        self._buffer_offset = 0
        self._closed = False

    def _append_next(self, target_bytes: int) -> bool:
        """Append the next source part to the buffer."""
        raise NotImplementedError

    def _reset_reader(self) -> None:
        """Reset subclass source position to the beginning."""
        raise NotImplementedError

    def _buffered_bytes(self) -> int:
        """Return unread bytes currently held by the reader."""
        return len(self._buffer) - self._buffer_offset

    def _discard_buffer(self) -> None:
        """Drop the backing allocation, optionally overwriting its contents first."""
        old_buffer = self._buffer
        self._buffer = bytearray()
        self._buffer_offset = 0
        if old_buffer and _secure_cleanup_enabled():
            _zero_bytearray_range(old_buffer, 0, len(old_buffer))
        old_buffer.clear()

    def _compact_buffer(self) -> None:
        """Discard the consumed prefix at an amortized frequency."""
        if self._buffer_offset == 0:
            return
        if self._buffer_offset == len(self._buffer):
            self._discard_buffer()
            return
        if self._buffer_offset >= _COMPACT_AFTER_BYTES and self._buffer_offset * 2 >= len(
            self._buffer
        ):
            if _secure_cleanup_enabled():
                _zero_bytearray_range(self._buffer, 0, self._buffer_offset)
            del self._buffer[: self._buffer_offset]
            self._buffer_offset = 0

    def read(self, max_bytes: int = -1, /) -> bytes:
        """Return up to max_bytes from the generated byte stream."""
        if self._closed:
            raise ValueError(f"I/O operation on closed {self._reader_name}")
        if max_bytes is None or max_bytes < 0:
            max_bytes = self._default_chunk_bytes
        if max_bytes == 0:
            return b""
        while self._buffered_bytes() < max_bytes:
            self._compact_buffer()
            before = len(self._buffer)
            if not self._append_next(max_bytes - self._buffered_bytes()):
                break
            if len(self._buffer) == before:
                break
        available = self._buffered_bytes()
        if available == 0:
            return b""
        read_size = min(max_bytes, available)
        start = self._buffer_offset
        self._buffer_offset += read_size
        view = memoryview(self._buffer)[start : self._buffer_offset]
        try:
            out = view.tobytes()
        finally:
            view.release()
        self._compact_buffer()
        return out

    def seek(self, offset: int) -> int:
        """Reset the generated byte stream to the beginning."""
        if offset != 0:
            raise ValueError(f"{self._reader_name} only supports seek(0)")
        self._reset_reader()
        self._discard_buffer()
        self._closed = False
        return 0

    def close(self) -> None:
        """Release transient buffered bytes."""
        if self._closed:
            return
        self._closed = True
        self._discard_buffer()

    def __del__(self) -> None:
        """Best-effort release transient buffered bytes."""
        if runtime_is_finalizing():
            return
        with suppress(Exception):
            self.close()
