# Defines native source ownership for schema-sanitizer targets.
#
# Keep this manifest explicit so packaging checks can verify every production
# translation unit is owned by a CMake target.

target_sources(
  ${_schema_sanitizer_pymod_target}
  PRIVATE cpp/src/api/python_abi3/_core_abi3.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_batch.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_finalize.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_formatters.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_schema.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_schema_payload.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_values.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_values_dictionary.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_values_nested.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_values_temporal.cc
          cpp/src/api/python_abi3/_core_abi3_arrow_direct_wrappers.cc
          cpp/src/api/python_abi3/_core_abi3_capsules.cc
          cpp/src/api/python_abi3/_core_abi3_coalesce_stream.cc
          cpp/src/api/python_abi3/_core_abi3_csv_nested_stream.cc
          cpp/src/api/python_abi3/_core_abi3_csv_nested_stream_columns.cc
          cpp/src/api/python_abi3/_core_abi3_csv_nested_stream_common.cc
          cpp/src/api/python_abi3/_core_abi3_csv_nested_stream_schema.cc
          cpp/src/api/python_abi3/_core_abi3_csv_writer.cc
          cpp/src/api/python_abi3/_core_abi3_file_metadata.cc
          cpp/src/api/python_abi3/_core_abi3_json_compact.cc
          cpp/src/api/python_abi3/_core_abi3_json_file_read.cc
          cpp/src/api/python_abi3/_core_abi3_json_file_compact.cc
          cpp/src/api/python_abi3/_core_abi3_json_value_tools.cc
          cpp/src/api/python_abi3/_core_abi3_jsonl_output_adapters.cc
          cpp/src/api/python_abi3/_core_abi3_jsonl_output_batch.cc
          cpp/src/api/python_abi3/_core_abi3_jsonl_output.cc
          cpp/src/api/python_abi3/_core_abi3_jsonl_writer.cc
          cpp/src/api/python_abi3/_core_abi3_module.cc
          cpp/src/api/python_abi3/_core_abi3_parquet_reader.cc
          cpp/src/api/python_abi3/_core_abi3_parquet_writer.cc
          cpp/src/api/python_abi3/_core_abi3_path_sources.cc
          cpp/src/api/python_abi3/_core_abi3_python_rows.cc
          cpp/src/api/python_abi3/_core_abi3_xml_folder_parts.cc
          cpp/src/api/python_abi3/_core_abi3_xml_folder.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_columns.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_stream.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_stream_builders.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_stream_columns.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_stream_common.cc
          cpp/src/api/python_abi3/_core_abi3_metadata_stream_schema.cc
          cpp/src/api/python_abi3/_core_abi3_reader.cc
          cpp/src/api/python_abi3/_core_abi3_registry_common.cc
          cpp/src/api/python_abi3/_core_abi3_registry_sinks_arrow.cc
          cpp/src/api/python_abi3/_core_abi3_registry_sinks_arrow_sources.cc
          cpp/src/api/python_abi3/_core_abi3_registry_sinks_source.cc
          cpp/src/api/python_abi3/_core_abi3_schema_registry.cc
          cpp/src/api/python_abi3/_core_abi3_schema_probe.cc
          cpp/src/api/python_abi3/_core_abi3_sink_helpers.cc
          cpp/src/api/python_abi3/_core_abi3_sinks.cc
          cpp/src/api/python_abi3/_core_abi3_sinks_source.cc
          cpp/src/api/python_abi3/_core_abi3_source_utils.cc
          cpp/src/api/python_abi3/_core_abi3_shared.cc
          cpp/src/api/python_abi3/_core_abi3_stream_lifecycle.cc
          cpp/src/api/python_abi3/_core_abi3_context_options.cc
          cpp/src/api/c/schema_sanitizer_c.cc
          cpp/src/api/c/schema_sanitizer_c_context.cc
          cpp/src/api/c/schema_sanitizer_c_context_stats.cc
          cpp/src/api/c/schema_sanitizer_c_sink.cc
          cpp/src/api/c/schema_sanitizer_c_sink_source.cc
          cpp/src/api/c/schema_sanitizer_c_sink_registry.cc
          cpp/src/api/c/schema_sanitizer_c_sink_registry_source.cc)

target_sources(
  sanitize_core
  PRIVATE cpp/src/core/logical_schema.cc
          cpp/src/core/ingest.cpp
          cpp/src/core/ingest_prepare.cc
          cpp/src/internal/pipeline/materialize.cc
          cpp/src/registry/registry.cpp
          cpp/src/metadata/file_metadata.cc
          cpp/src/schema_registry/schema_registry.cc
          cpp/src/schema_registry/schema_registry_json.cc
          cpp/src/schema_registry/schema_registry_json_schema_write.cc
          cpp/src/schema_registry/schema_registry_json_write.cc
          cpp/src/schema_registry/schema_registry_types.cc
          cpp/src/internal/memory/memory_pool.cc
          cpp/src/internal/pipeline/direct_materializer.cc
          cpp/src/internal/pipeline/ingest_stream_source.cc
          cpp/src/internal/pipeline/infer_depth.cc
          cpp/src/internal/pipeline/infer_scan_common.cc
          cpp/src/internal/arrow/arrow_formatters.cc
          cpp/src/internal/arrow/arrow_formatters_binary.cc
          cpp/src/internal/arrow/arrow_formatters_decimal.cc
          cpp/src/internal/arrow/arrow_formatters_temporal.cc
          cpp/src/core/diagnostics.cc
          cpp/src/internal/core/value_view_util.cc
          cpp/src/planning/options.cpp
          cpp/src/planning/options_temporal.cc
          cpp/src/internal/planning/options_temporal_simple.cc
          cpp/src/internal/planning/options_temporal_simple_parts.cc
          cpp/src/planning/options_temporal_regex.cc
          cpp/src/planning/options_temporal_regex_parts.cc
          cpp/src/planning/options_io.cc
          cpp/src/planning/io/options_schema_io.cc
          cpp/src/planning/field_name_sanitizer.cc
          cpp/src/internal/planning/field_name_collision.cc
          cpp/src/internal/planning/field_name_policy.cc
          cpp/src/internal/planning/planned_name_matcher.cc
          cpp/src/internal/planning/variant_field_names.cc
          cpp/src/planning/plan.cpp
          cpp/src/planning/execution_context.cc
          cpp/src/core/value_view.cpp
          cpp/src/core/chunk_source.cpp
          cpp/src/frontends/json_ondemand.cc
          cpp/src/frontends/json_ondemand_iter.cc
          cpp/src/internal/parsing/json_ondemand_scan.cc
          cpp/src/internal/parsing/json_string_decode.cc
          cpp/src/core/primitives_numeric.cpp
          cpp/src/core/primitives_temporal.cpp
          cpp/src/internal/csv/csv_stream_writer.cc
          cpp/src/internal/parquet/parquet_footer_reader.cc
          cpp/src/internal/parquet/parquet_stream_writer.cc
          cpp/src/internal/json/json_write.cc
          cpp/src/internal/json/jsonl_stream_writer.cc
          cpp/src/internal/json/jsonl_stream_writer_schema.cc
          cpp/src/internal/json/jsonl_value_writer.cc
          cpp/src/internal/json/jsonl_value_writer_nested.cc
          cpp/src/internal/json/jsonl_value_writer_scalar.cc
          cpp/src/internal/json/jsonl_value_writer_string.cc
          cpp/src/internal/json/jsonl_value_writer_temporal.cc
          cpp/src/internal/pipeline/cdata_export.cc
          cpp/src/internal/pipeline/cdata_schema_builder.cc
          cpp/src/internal/pipeline/cdata_schema_builder_nodes.cc
          cpp/src/internal/pipeline/cdata_stream_utils.cc
          cpp/src/internal/memory/arena.cc
          cpp/src/internal/memory/pool_resource.cc
          cpp/src/internal/frontends/csv_column_projection.cc
          cpp/src/internal/frontends/json_root_field_filter.cc
          cpp/src/internal/parsing/xml_document.cc
          cpp/src/internal/parsing/xml_value_model.cc
          cpp/src/internal/parsing/streaming/xml_row_tag_scanner.cc
          cpp/src/internal/parsing/streaming/xml_row_tag_scanner_buffer.cc
          cpp/src/internal/parsing/streaming/xml_row_tag_scanner_utils.cc
          cpp/src/frontends/json_text_frontend.cc
          cpp/src/frontends/xml_frontend.cc
          cpp/src/frontends/csv_frontend.cc
          cpp/src/internal/parsing/streaming/csv_record_span_scanner.cc
          cpp/src/internal/parsing/streaming/csv_streaming_scanner.cc
          cpp/src/internal/parsing/streaming/json_streaming_scanner.cc
          cpp/src/internal/parsing/streaming/json_value_span_scanner.cc
          cpp/src/internal/pipeline/infer.cc
          cpp/src/internal/pipeline/infer_schema.cc
          cpp/src/internal/pipeline/infer_stats.cc
          cpp/src/planning/schema_evolution.cc
          cpp/src/internal/build/build.cc
          cpp/src/internal/build/build_builders.cc
          cpp/src/internal/build/build_nested_builders.cc
          cpp/src/internal/build/build_scalar_builders.cc
          cpp/src/internal/build/build_scalar_conversion.cc
          cpp/src/internal/build/build_conversion.cc
          cpp/src/internal/build/build_object_field_snapshot.cc
          cpp/src/internal/build/build_struct_conversion.cc
          cpp/src/internal/build/build_variant_routing.cc
          cpp/src/internal/build/build_field_lookup.cc
          cpp/src/internal/build/build_value_format.cc
          cpp/src/internal/build/build_rows.cc)
